### ISSUE TITLE
TypeError: lettersScrollBar.height is not a function

### ISSUE THREAD

**Issue by kushal555** [raiseandfall/ng-alphabet-indexer#1]
Hi, 

I Just download your plugin and install the bower components. But when i run the index.html from example folder i found the issue 

`TypeError: lettersScrollBar.height is not a function`

**Comment by kushal555** [comment]
Okay, I got the point to solve the bug.
Just include the jquery file.

**Comment by raiseandfall** [comment]
Hey @kushal555 
Glad you figured it out.
Also you're welcome to open PR with updates, this was started a long time ago and got never finished.
